/**
 * Pure HTML + plain-text renderers for a cryptosweep Report, intended for
 * email delivery via Resend. Inline CSS only; no JavaScript.
 */
import type { Finding, Report, Severity } from "../report";

const SEVERITY_GROUPS: readonly Exclude<Severity, "info">[] = ["critical", "high", "medium", "low"];

const SEVERITY_COLOR: Record<Severity, string> = {
  critical: "#b91c1c",
  high: "#c2410c",
  medium: "#a16207",
  low: "#1d4ed8",
  info: "#475569",
};

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
  info: "Info",
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function groupBySeverity(findings: readonly Finding[]): Map<Severity, Finding[]> {
  const groups = new Map<Severity, Finding[]>();
  for (const finding of findings) {
    const bucket = groups.get(finding.severity) ?? [];
    bucket.push(finding);
    groups.set(finding.severity, bucket);
  }
  return groups;
}

function renderFindingHtml(finding: Finding): string {
  const color = SEVERITY_COLOR[finding.severity];
  return [
    `<div style="margin:0 0 16px 0;padding:12px 14px;border-left:4px solid ${color};background:#f8fafc;">`,
    `<div style="font:600 14px/1.4 -apple-system,Segoe UI,sans-serif;color:#0f172a;">${escapeHtml(finding.id)} — ${escapeHtml(finding.title)}</div>`,
    `<div style="font:13px/1.5 -apple-system,Segoe UI,sans-serif;color:#334155;margin-top:4px;">`,
    `<strong>Evidence:</strong> ${escapeHtml(finding.evidence)}<br/>`,
    `<strong>PQ status:</strong> ${escapeHtml(finding.pq_status)}<br/>`,
    `<strong>NIST-aligned remediation:</strong> ${escapeHtml(finding.recommendation)}`,
    `</div></div>`,
  ].join("");
}

export function renderHtml(report: Report): string {
  const groups = groupBySeverity(report.findings);
  const { summary } = report;
  const sections = SEVERITY_GROUPS.filter((sev) => (groups.get(sev) ?? []).length > 0)
    .map((sev) => {
      const heading = `<h2 style="font:600 16px/1.3 -apple-system,Segoe UI,sans-serif;color:${SEVERITY_COLOR[sev]};margin:20px 0 8px;">${SEVERITY_LABEL[sev]} (${(groups.get(sev) ?? []).length})</h2>`;
      const body = (groups.get(sev) ?? []).map(renderFindingHtml).join("");
      return heading + body;
    })
    .join("");
  const empty = report.findings.length === 0
    ? `<p style="font:14px/1.5 -apple-system,Segoe UI,sans-serif;color:#0f172a;">No quantum-vulnerable primitives detected.</p>`
    : "";
  return [
    `<!doctype html><html><body style="margin:0;padding:0;background:#eef2f7;">`,
    `<div style="max-width:640px;margin:0 auto;padding:24px;background:#ffffff;font-family:-apple-system,Segoe UI,sans-serif;color:#0f172a;">`,
    `<div style="border-bottom:2px solid #0f172a;padding-bottom:12px;margin-bottom:16px;">`,
    `<div style="font:700 20px/1.2 -apple-system,Segoe UI,sans-serif;color:#0f172a;">cryptosweep PQ readiness report</div>`,
    `<div style="font:13px/1.5 -apple-system,Segoe UI,sans-serif;color:#475569;margin-top:4px;">Target: ${escapeHtml(report.target)} &middot; Scanned: ${escapeHtml(report.scanned_at)}</div>`,
    `</div>`,
    `<p style="font:14px/1.5 -apple-system,Segoe UI,sans-serif;color:#0f172a;margin:0 0 12px;">Total findings: ${summary.findings} (critical ${summary.critical}, high ${summary.high}, medium ${summary.medium}, low ${summary.low}).</p>`,
    empty,
    sections,
    `<p style="font:12px/1.5 -apple-system,Segoe UI,sans-serif;color:#64748b;margin-top:24px;border-top:1px solid #e2e8f0;padding-top:12px;">Generated by cryptosweep. Remediation guidance aligned with NIST SP 800-208 / FIPS 203 / FIPS 204.</p>`,
    `</div></body></html>`,
  ].join("");
}

function renderFindingText(finding: Finding): string {
  return [
    `  [${finding.id}] ${finding.title}`,
    `    Evidence: ${finding.evidence}`,
    `    PQ status: ${finding.pq_status}`,
    `    NIST-aligned remediation: ${finding.recommendation}`,
  ].join("\n");
}

export function renderText(report: Report): string {
  const groups = groupBySeverity(report.findings);
  const { summary } = report;
  const lines: string[] = [
    `cryptosweep PQ readiness report`,
    `Target: ${report.target}`,
    `Scanned: ${report.scanned_at}`,
    ``,
    `Total findings: ${summary.findings} (critical ${summary.critical}, high ${summary.high}, medium ${summary.medium}, low ${summary.low}).`,
    ``,
  ];
  if (report.findings.length === 0) {
    lines.push(`No quantum-vulnerable primitives detected.`);
  }
  for (const sev of SEVERITY_GROUPS) {
    const bucket = groups.get(sev) ?? [];
    if (bucket.length === 0) continue;
    lines.push(`${SEVERITY_LABEL[sev]} (${bucket.length})`);
    lines.push("-".repeat(`${SEVERITY_LABEL[sev]} (${bucket.length})`.length));
    for (const finding of bucket) lines.push(renderFindingText(finding), "");
  }
  lines.push(`-- Generated by cryptosweep. Remediation guidance aligned with NIST SP 800-208 / FIPS 203 / FIPS 204.`);
  return lines.join("\n");
}
