/**
 * Pure HTML + plain-text renderers for a cryptosweep Report, intended for
 * email delivery via Resend. Inline CSS only; no JavaScript.
 *
 * The report is loaded from a JSON file, so every field, counts included, is
 * treated as untrusted: HTML output escapes all of them and plain-text output
 * makes control characters visible.
 */
import { NO_FINDINGS_MESSAGE, coverageLines, emptyResultNote, sanitizeText } from "../report";
import type { Finding, Report, Severity } from "../report";

const SEVERITY_GROUPS: readonly Exclude<Severity, "info">[] = ["critical", "high", "medium", "low"];

const SEVERITY_COLOR: Record<Severity, string> = {
  critical: "#b91c1c",
  high: "#c2410c",
  medium: "#a16207",
  low: "#1d4ed8",
  info: "#475569",
};

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
  info: "Info",
};

function escapeHtml(value: unknown): string {
  return sanitizeText(String(value))
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** A plain-text field: any value, stringified, with control characters made visible. */
function plain(value: unknown): string {
  return sanitizeText(String(value));
}

function groupBySeverity(findings: readonly Finding[]): Map<Severity, Finding[]> {
  const groups = new Map<Severity, Finding[]>();
  for (const finding of findings) {
    const bucket = groups.get(finding.severity) ?? [];
    bucket.push(finding);
    groups.set(finding.severity, bucket);
  }
  return groups;
}

function renderFindingHtml(finding: Finding): string {
  const color = SEVERITY_COLOR[finding.severity];
  return [
    `<div style="margin:0 0 16px 0;padding:12px 14px;border-left:4px solid ${color};background:#f8fafc;">`,
    `<div style="font:600 14px/1.4 -apple-system,Segoe UI,sans-serif;color:#0f172a;">${escapeHtml(finding.id)}, ${escapeHtml(finding.title)}</div>`,
    `<div style="font:13px/1.5 -apple-system,Segoe UI,sans-serif;color:#334155;margin-top:4px;">`,
    `<strong>Evidence:</strong> ${escapeHtml(finding.evidence)}<br/>`,
    `<strong>PQ status:</strong> ${escapeHtml(finding.pq_status)}<br/>`,
    `<strong>NIST-aligned remediation:</strong> ${escapeHtml(finding.recommendation)}`,
    `</div></div>`,
  ].join("");
}

export function renderHtml(report: Report): string {
  const groups = groupBySeverity(report.findings);
  const { summary } = report;
  const sections = SEVERITY_GROUPS.filter((sev) => (groups.get(sev) ?? []).length > 0)
    .map((sev) => {
      const heading = `<h2 style="font:600 16px/1.3 -apple-system,Segoe UI,sans-serif;color:${SEVERITY_COLOR[sev]};margin:20px 0 8px;">${SEVERITY_LABEL[sev]} (${(groups.get(sev) ?? []).length})</h2>`;
      const body = (groups.get(sev) ?? []).map(renderFindingHtml).join("");
      return heading + body;
    })
    .join("");
  const empty = report.findings.length === 0 ? renderEmptyHtml(report) : "";
  return [
    `<!doctype html><html><body style="margin:0;padding:0;background:#eef2f7;">`,
    `<div style="max-width:640px;margin:0 auto;padding:24px;background:#ffffff;font-family:-apple-system,Segoe UI,sans-serif;color:#0f172a;">`,
    `<div style="border-bottom:2px solid #0f172a;padding-bottom:12px;margin-bottom:16px;">`,
    `<div style="font:700 20px/1.2 -apple-system,Segoe UI,sans-serif;color:#0f172a;">cryptosweep PQ readiness report</div>`,
    `<div style="font:13px/1.5 -apple-system,Segoe UI,sans-serif;color:#475569;margin-top:4px;">Target: ${escapeHtml(report.target)} &middot; Scanned: ${escapeHtml(report.scanned_at)}</div>`,
    `</div>`,
    `<p style="font:14px/1.5 -apple-system,Segoe UI,sans-serif;color:#0f172a;margin:0 0 12px;">Total findings: ${escapeHtml(summary.findings)} (critical ${escapeHtml(summary.critical)}, high ${escapeHtml(summary.high)}, medium ${escapeHtml(summary.medium)}, low ${escapeHtml(summary.low)}).</p>`,
    empty,
    sections,
    `<p style="font:12px/1.5 -apple-system,Segoe UI,sans-serif;color:#64748b;margin-top:24px;border-top:1px solid #e2e8f0;padding-top:12px;">Generated by cryptosweep. Remediation guidance aligned with NIST SP 800-208 / FIPS 203 / FIPS 204.</p>`,
    `</div></body></html>`,
  ].join("");
}

/** The scoped empty state: what ran, not a blanket all-clear. */
function renderEmptyHtml(report: Report): string {
  const style = "font:14px/1.5 -apple-system,Segoe UI,sans-serif;color:#0f172a;";
  const coverage = report.coverage?.length
    ? `<ul style="${style}">${coverageLines(report.coverage).map((line) => `<li>${escapeHtml(line)}</li>`).join("")}</ul>`
    : "";
  return `<p style="${style}">${escapeHtml(NO_FINDINGS_MESSAGE)} ${escapeHtml(emptyResultNote(report))}</p>${coverage}`;
}

function renderFindingText(finding: Finding): string {
  return [
    `  [${plain(finding.id)}] ${plain(finding.title)}`,
    `    Evidence: ${plain(finding.evidence)}`,
    `    PQ status: ${plain(finding.pq_status)}`,
    `    NIST-aligned remediation: ${plain(finding.recommendation)}`,
  ].join("\n");
}

export function renderText(report: Report): string {
  const groups = groupBySeverity(report.findings);
  const { summary } = report;
  const lines: string[] = [
    `cryptosweep PQ readiness report`,
    `Target: ${plain(report.target)}`,
    `Scanned: ${plain(report.scanned_at)}`,
    ``,
    `Total findings: ${plain(summary.findings)} (critical ${plain(summary.critical)}, high ${plain(summary.high)}, medium ${plain(summary.medium)}, low ${plain(summary.low)}).`,
    ``,
  ];
  if (report.findings.length === 0) {
    lines.push(NO_FINDINGS_MESSAGE, emptyResultNote(report));
    for (const line of coverageLines(report.coverage ?? [])) lines.push(`  - ${plain(line)}`);
    lines.push(``);
  }
  for (const sev of SEVERITY_GROUPS) {
    const bucket = groups.get(sev) ?? [];
    if (bucket.length === 0) continue;
    lines.push(`${SEVERITY_LABEL[sev]} (${bucket.length})`);
    lines.push("-".repeat(`${SEVERITY_LABEL[sev]} (${bucket.length})`.length));
    for (const finding of bucket) lines.push(renderFindingText(finding), "");
  }
  lines.push(`-- Generated by cryptosweep. Remediation guidance aligned with NIST SP 800-208 / FIPS 203 / FIPS 204.`);
  return lines.join("\n");
}
