/**
 * Self-contained HTML report viewer.
 *
 * cryptosweep is a CLI, so its operational surface is honest to that: a single
 * file with no external requests, no bundler, and no network — the report JSON
 * is embedded and rendered client-side into an interactive cryptographic
 * inventory (summary, filters, drill-down to evidence and citations).
 *
 * Security: scanned repositories are untrusted, so every value from a finding is
 * inserted with textContent, never innerHTML. There is no path by which scanned
 * content becomes markup.
 */
import type { Report } from "../report";
import { VERSION } from "../version";

/** Render a report as a single self-contained, offline HTML document. */
export function toHtml(report: Report): string {
  // Escape only the </script> boundary so the JSON island cannot break out.
  const data = JSON.stringify(report).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>cryptosweep — ${escapeHtml(report.target)}</title>
<style>${STYLE}</style>
</head>
<body>
<header>
  <div class="brand">cryptosweep</div>
  <div class="meta">
    <span class="target" id="target"></span>
    <span class="when" id="when"></span>
  </div>
</header>
<section class="tiles" id="tiles" aria-label="Summary"></section>
<section class="controls">
  <input type="search" id="q" placeholder="Search findings, evidence, algorithms…" aria-label="Search" />
  <div class="filters" id="filters"></div>
</section>
<main>
  <div class="col">
    <h2>Findings <span class="count" id="fcount"></span></h2>
    <ol class="findings" id="findings"></ol>
  </div>
  <aside class="col">
    <h2>Cryptographic assets</h2>
    <ul class="assets" id="assets"></ul>
  </aside>
</main>
<footer>Generated by cryptosweep v${VERSION}. Confidence reflects how the evidence was derived — <em>confirmed</em> is parsed structure; <em>low</em> is a context-sensitive heuristic. Not a substitute for a credentialed cryptographer's review.</footer>
<script id="data" type="application/json">${data}</script>
<script>${SCRIPT}</script>
</body>
</html>
`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const STYLE = `
:root{--bg:#0b0e14;--panel:#11161f;--panel2:#161c28;--line:#232c3b;--fg:#e6edf6;--muted:#8b98ad;
--crit:#ff5c6c;--high:#ff9f45;--med:#ffd23f;--low:#4aa3ff;--info:#5b6b82;--safe:#38d39f;--accent:#6ea8fe;}
:root[data-theme=light]{--bg:#f6f8fb;--panel:#fff;--panel2:#f0f3f8;--line:#dde3ec;--fg:#111823;--muted:#5a6678;--info:#9aa7ba;}
*{box-sizing:border-box}
body{margin:0;font:14px/1.5 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:var(--fg);background:var(--bg);}
header{display:flex;align-items:baseline;gap:16px;padding:18px 24px;border-bottom:1px solid var(--line);background:var(--panel);position:sticky;top:0;z-index:2}
.brand{font-weight:700;letter-spacing:-.02em;font-size:16px}
.meta{display:flex;gap:16px;flex-wrap:wrap;color:var(--muted);font-size:13px}
.target{color:var(--fg);font-weight:600}
.tiles{display:flex;gap:10px;flex-wrap:wrap;padding:18px 24px}
.tile{flex:1 1 120px;min-width:120px;background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:12px 14px}
.tile .n{font-size:26px;font-weight:700;line-height:1}
.tile .l{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.06em;margin-top:6px}
.tile.crit{border-color:var(--crit)}.tile.crit .n{color:var(--crit)}
.tile.high .n{color:var(--high)}.tile.med .n{color:var(--med)}.tile.pq .n{color:var(--crit)}
.controls{display:flex;gap:12px;flex-wrap:wrap;align-items:center;padding:0 24px 12px}
#q{flex:1 1 280px;min-width:220px;background:var(--panel2);border:1px solid var(--line);color:var(--fg);border-radius:8px;padding:9px 12px;font-size:13px}
#q:focus{outline:2px solid var(--accent)}
.filters{display:flex;gap:6px;flex-wrap:wrap}
.chip{cursor:pointer;user-select:none;border:1px solid var(--line);background:var(--panel2);color:var(--muted);border-radius:999px;padding:5px 11px;font-size:12px}
.chip[aria-pressed=true]{color:var(--fg);border-color:var(--accent);background:color-mix(in srgb,var(--accent) 18%,var(--panel2))}
main{display:grid;grid-template-columns:1fr 300px;gap:20px;padding:8px 24px 40px}
@media(max-width:820px){main{grid-template-columns:1fr}}
h2{font-size:13px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);margin:8px 0}
.count{color:var(--muted);font-weight:400}
.findings{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:8px}
.f{background:var(--panel);border:1px solid var(--line);border-left-width:3px;border-radius:9px;overflow:hidden}
.f.crit{border-left-color:var(--crit)}.f.high{border-left-color:var(--high)}.f.med{border-left-color:var(--med)}
.f.low{border-left-color:var(--low)}.f.info{border-left-color:var(--info)}
.f>.row{display:flex;gap:10px;align-items:center;padding:11px 14px;cursor:pointer}
.f .title{font-weight:600;flex:1;min-width:0}
.badge{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;padding:2px 7px;border-radius:6px;white-space:nowrap}
.badge.crit{background:var(--crit);color:#1a0206}.badge.high{background:var(--high);color:#241100}.badge.med{background:var(--med);color:#241f00}
.badge.low{background:var(--low);color:#001328}.badge.info{background:var(--info);color:#fff}
.tag{font-size:11px;color:var(--muted);border:1px solid var(--line);border-radius:6px;padding:2px 6px;white-space:nowrap}
.tag.vuln{color:var(--crit);border-color:color-mix(in srgb,var(--crit) 50%,var(--line))}
.tag.safe{color:var(--safe)}.tag.trans{color:var(--low)}
.detail{display:none;padding:0 14px 14px;border-top:1px solid var(--line);color:var(--muted)}
.f.open .detail{display:block}
.detail dt{color:var(--fg);font-weight:600;margin-top:10px;font-size:12px;text-transform:uppercase;letter-spacing:.05em}
.detail dd{margin:3px 0 0}
.detail a{color:var(--accent)}
.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px;word-break:break-all}
.assets{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:6px}
.asset{display:flex;justify-content:space-between;gap:8px;align-items:center;background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:8px 11px}
.asset .an{font-family:ui-monospace,Menlo,monospace;font-size:12.5px}
.empty{color:var(--muted);padding:16px;border:1px dashed var(--line);border-radius:9px;text-align:center}
`;

const SCRIPT = `
(function(){
  var report = JSON.parse(document.getElementById('data').textContent);
  var SEV = ['critical','high','medium','low','info'];
  var SEVCLS = {critical:'crit',high:'high',medium:'med',low:'low',info:'info'};
  var state = { q:'', sev:new Set(), pq:new Set() };

  document.getElementById('target').textContent = report.target;
  document.getElementById('when').textContent = 'scanned ' + report.scanned_at;

  // Summary tiles.
  var s = report.summary, tiles = document.getElementById('tiles');
  var pqVuln = report.findings.filter(function(f){return f.pq_status==='vulnerable';}).length;
  [['crit','Critical',s.critical],['high','High',s.high],['med','Medium',s.medium],['','Low',s.low],['','Info',s.info],['pq','PQ-vulnerable',pqVuln]]
    .forEach(function(t){var d=document.createElement('div');d.className='tile '+t[0];var n=document.createElement('div');n.className='n';n.textContent=t[2];var l=document.createElement('div');l.className='l';l.textContent=t[1];d.appendChild(n);d.appendChild(l);tiles.appendChild(d);});

  // Filter chips.
  var filters = document.getElementById('filters');
  SEV.forEach(function(sv){ filters.appendChild(chip(sv, state.sev)); });
  ['vulnerable','transitional','safe','unknown'].forEach(function(p){ filters.appendChild(chip(p, state.pq)); });
  function chip(label, set){var c=document.createElement('button');c.className='chip';c.type='button';c.textContent=label;c.setAttribute('aria-pressed','false');
    c.addEventListener('click',function(){var on=c.getAttribute('aria-pressed')==='true';c.setAttribute('aria-pressed',(!on).toString());if(on)set.delete(label);else set.add(label);render();});return c;}

  document.getElementById('q').addEventListener('input',function(e){state.q=e.target.value.toLowerCase();render();});

  // Asset inventory (one row per distinct algorithm).
  var assets = document.getElementById('assets'); var seen={};
  report.findings.forEach(function(f){ if(f.algorithm && !seen[f.algorithm]){seen[f.algorithm]=f;} });
  var akeys = Object.keys(seen);
  if(!akeys.length){ assets.innerHTML=''; var e=document.createElement('li');e.className='empty';e.textContent='No algorithms inventoried.';assets.appendChild(e); }
  akeys.forEach(function(k){var f=seen[k];var li=document.createElement('li');li.className='asset';var n=document.createElement('span');n.className='an';n.textContent=k;var t=document.createElement('span');t.className='tag '+pqcls(f.pq_status);t.textContent=f.pq_status;li.appendChild(n);li.appendChild(t);assets.appendChild(li);});

  function pqcls(p){return p==='vulnerable'?'vuln':p==='safe'?'safe':p==='transitional'?'trans':'';}

  function matches(f){
    if(state.sev.size && !state.sev.has(f.severity)) return false;
    if(state.pq.size && !state.pq.has(f.pq_status)) return false;
    if(state.q){var hay=(f.title+' '+f.evidence+' '+(f.algorithm||'')+' '+f.recommendation).toLowerCase();if(hay.indexOf(state.q)<0)return false;}
    return true;
  }

  function render(){
    var list=document.getElementById('findings'); list.textContent='';
    var shown=report.findings.filter(matches);
    document.getElementById('fcount').textContent='('+shown.length+' of '+report.findings.length+')';
    if(!shown.length){var e=document.createElement('div');e.className='empty';e.textContent='No findings match the current filters.';list.appendChild(e);return;}
    shown.forEach(function(f){
      var li=document.createElement('li'); li.className='f '+SEVCLS[f.severity];
      var row=document.createElement('div'); row.className='row';
      row.appendChild(el('span','badge '+SEVCLS[f.severity],f.severity));
      row.appendChild(el('span','title',f.title));
      if(f.confidence) row.appendChild(el('span','tag',f.confidence));
      row.appendChild(el('span','tag '+pqcls(f.pq_status),f.pq_status));
      row.addEventListener('click',function(){li.classList.toggle('open');});
      li.appendChild(row);
      var d=document.createElement('dl'); d.className='detail';
      addField(d,'Evidence',f.evidence,true);
      if(f.algorithm) addField(d,'Algorithm',f.algorithm,true);
      addField(d,'Recommendation',f.recommendation,false);
      if(f.references&&f.references.length){var dt=el('dt','','References');var dd=document.createElement('dd');f.references.forEach(function(r,i){if(i)dd.appendChild(document.createTextNode(' · '));if(r.url){var a=document.createElement('a');a.href=r.url;a.textContent=r.label;a.rel='noopener noreferrer';a.target='_blank';dd.appendChild(a);}else{dd.appendChild(document.createTextNode(r.label));}});d.appendChild(dt);d.appendChild(dd);}
      addField(d,'Rule',(f.ruleId||f.id)+'  ·  '+f.id,true);
      li.appendChild(d);
      list.appendChild(li);
    });
  }
  function el(tag,cls,txt){var e=document.createElement(tag);if(cls)e.className=cls;e.textContent=txt;return e;}
  function addField(dl,label,value,mono){dl.appendChild(el('dt','',label));var dd=el('dd',mono?'mono':'',value);dl.appendChild(dd);}

  render();
})();
`;
