/**
 * Bundle the Blueprint (React) report viewer into a single, offline,
 * self-contained HTML shell and emit it as a committed base64 module that the
 * CLI decodes at scan time. Everything (React, Blueprint, CSS) is inlined; the
 * shell makes no network request.
 *
 * Run via `pnpm build:viewer` (also invoked by `pnpm prebuild`).
 */
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const outdir = mkdtempSync(join(tmpdir(), "csw-viewer-"));

await build({
  entryPoints: ["viewer/main.tsx"],
  bundle: true,
  minify: true,
  format: "iife",
  jsx: "automatic",
  target: ["es2020"],
  outdir,
  loader: { ".css": "css" },
  // Compile React in production mode: smaller, no dev warnings, no `process` ref.
  define: { "process.env.NODE_ENV": '"production"' },
  logLevel: "warning",
});

// Neutralize any literal </script> inside bundled string/regex literals so it
// cannot close the inlined <script> tag early. Valid because it only appears
// inside such literals, where <\/script is equivalent.
const escapeScript = (s) => s.replace(/<\/(script)/gi, "<\\/$1");

const js = escapeScript(readFileSync(join(outdir, "main.js"), "utf8"));
const css = readFileSync(join(outdir, "main.css"), "utf8");

const shell = `<!doctype html>
<html lang="en" class="bp5-dark">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>cryptosweep report</title>
<style>${css}</style>
</head>
<body class="bp5-dark">
<div id="root"></div>
<script id="data" type="application/json">__CRYPTOSWEEP_DATA__</script>
<script>${js}</script>
</body>
</html>`;

// Fail loudly if the bundle would reach the network (breaks the offline guarantee).
const external = shell.match(/https?:\/\/[^"')\s]+\.(?:js|css|woff2?|png|jpe?g|svg)/i);
if (external) {
  throw new Error(`Viewer bundle references an external asset (${external[0]}); it must be fully inlined.`);
}

const b64 = Buffer.from(shell, "utf8").toString("base64");
const module = `/* GENERATED by scripts/build-viewer.mjs — do not edit by hand.
 * The Blueprint (Apache-2.0) + React report viewer, bundled and inlined. */
export const VIEWER_SHELL_B64 =
  ${JSON.stringify(b64)};
export const VIEWER_DATA_PLACEHOLDER = "__CRYPTOSWEEP_DATA__";
`;

writeFileSync("src/output/viewer-shell.ts", module);
console.log(
  `viewer shell: ${(shell.length / 1024).toFixed(0)} KB (js ${(js.length / 1024).toFixed(0)} KB, css ${(css.length / 1024).toFixed(0)} KB)`,
);
